      - name: Generate Driver IPK Config
        run: |
          cd openwrt
          # 1. 必须拉取和你官方固件版本完全一致的源码（你现在的 v24.10.5 是对的）
          curl -fsSL https://raw.githubusercontent.com/immortalwrt/immortalwrt/v24.10.5/config/x86/64 > .config
          
          # 2. 只选中网卡驱动和相关固件
          echo "CONFIG_PACKAGE_kmod-atlantic=m" >> .config
          echo "CONFIG_PACKAGE_linux-firmware-aquantia=m" >> .config
          
          # 3. 补齐依赖
          make defconfig
